language: ruby
rvm:
  - 2.4.4

cache:
  directories:
    - vendor/bundle
    - node_modules

bundler_args: --without production

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails test
